import type {Locale} from '../../types'

export async function buildLocalesImporter(locales: Locale[]) {
  const imports: string[] = []
  const identifiers: string[] = []

  for (const locale of locales) {
    imports.push(`import {${locale.exportName}} from '${locale.packageName}'`)
    identifiers.push(locale.exportName)
  }

  const content = imports.join('\n')
  const exported = `export const locales = [${identifiers.map((id) => `${id}()`).join(', ')}]`
  const banner = `// This file is auto-generated by scripts/studioLocales.ts`
  const code = `${banner}\n${content}\n\n${exported}\n`

  return code
}
