packages:
  - 'apps/*'
  - 'packages/*'
  - 'locales/*'

allowBuilds:
  esbuild: false

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@portabletext/*'
  - '@sanity/*'
  - '@types/*'
  - 'groq'
  - 'groq-js'
  - 'sanity'
  # Renovate security update: js-yaml@4.3.0 || 4.3.1
  - js-yaml@4.3.0 || 4.3.1
  # Renovate dependency update: @sanity/vision@6.9.0 -> @sanity/client@get-it@8.8.3
  - get-it@8.8.3
