// This file is auto-generated by scripts/studioLocales.ts
import {deLocale} from '@sanity/locale-de'
import {esLocale} from '@sanity/locale-es'
import {frFRLocale} from '@sanity/locale-fr-fr'
import {jpLocale} from '@sanity/locale-jp'
import {koLocale} from '@sanity/locale-ko'
import {noNBLocale} from '@sanity/locale-no-nb'
import {ptBRLocale} from '@sanity/locale-pt-br'

export const locales = [
  deLocale(),
  esLocale(),
  frFRLocale(),
  jpLocale(),
  koLocale(),
  noNBLocale(),
  ptBRLocale(),
]
