// This file is auto-generated by scripts/studioLocales.ts
import {deLocale} from '@sanity/locale-de'
import {esLocale} from '@sanity/locale-es'
import {frFRLocale} from '@sanity/locale-fr-fr'
import {isLocale} from '@sanity/locale-is'
import {itLocale} from '@sanity/locale-it'
import {jpLocale} from '@sanity/locale-jp'
import {koLocale} from '@sanity/locale-ko'
import {noNBLocale} from '@sanity/locale-no-nb'
import {noNNLocale} from '@sanity/locale-no-nn'
import {ptBRLocale} from '@sanity/locale-pt-br'
import {ptPTLocale} from '@sanity/locale-pt-pt'

export const locales = [
  deLocale(),
  esLocale(),
  frFRLocale(),
  isLocale(),
  itLocale(),
  jpLocale(),
  koLocale(),
  noNBLocale(),
  noNNLocale(),
  ptBRLocale(),
  ptPTLocale(),
]
