name: Nudge stale PRs
'on':
  workflow_dispatch:
  schedule:
    # Every 12 hours
    - cron: '0 */12 * * *'
jobs:
  nudge-stale:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install pnpm, Node.js and dependencies
        uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ vars.ECOSPARK_CLIENT_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}

      - name: Nudge stale PRs
        run: pnpm run ci:nudge-stale
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
